### ISSUE TITLE
Number of People Joined the Sessions are 0 and not exact

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [hackclub/slash-z#64]
Number of Peoples who joined the sessions are not right. Sometime it says 0 people joined but there are like more than 10 peoples are joined.

**Comment by YodaLightsabr** [comment]
Ahhh I just realized I might've caused this. It started happening on June 22nd which is when I merged the hack night counter. I'll take a deeper look into this.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
Yeah sure, Thanks.

**Comment by grymmy** [comment]
@Muhammad-Ahsan-Rasheed I am not able to understand the issue here.  I am closing this issue as it has not been fixed in over a year, and also because I cannot understand it.  If you can please provide additional details on the thread here on how to reproduce this issue, and where exactly in the slash-z usage flow it occurs, please do so and re-open the issue.
